version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/yaml
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.13
  - dependency-name: phan/phan
    versions:
    - 4.0.1
  - dependency-name: symfony/http-kernel
    versions:
    - 4.4.18
  - dependency-name: symfony/http-foundation
    versions:
    - 4.4.18
  - dependency-name: solarium/solarium
    versions:
    - 6.0.4
  - dependency-name: mockery/mockery
    versions:
    - 1.4.2
