build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
filter:
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'
        - '.phan/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
