language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3

env:
  global:
    - SERVER_REDIS_ON=true

services:
  - memcached
  - redis-server

before_script:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

after_success:
# Submit coverage report to https://codecov.io
- bash <(curl -s https://codecov.io/bash)

script: 
  - ./vendor/bin/phpunit ./tests/ --coverage-clover=coverage.xml
  - ./vendor/bin/phpcs ./src/
